// grab the mongoose module
var mongoose = require('mongoose');

// define the schema for our user model
var quoteSchema = mongoose.Schema({
	name: String,
	userId: String,
	createdOn: String,
    email: String,
	fromAddress: String,
	fromAddressLine: String,
	toAddress: String,
	toAddressLine: String,
	floorsFrom: Number,
	parkDistFrom: Number,
	liftFrom: Boolean,
	floorsTo: Number,
	parkDistTo: Number,
	liftTo: Boolean,
	cubicVol: Number,
	cubicVolMap: {},
	itemData: {},
	dateTime: String,
	distance: Number,
	distMiles: Number,
	a2bDist: Number,
	b2cDist: Number,
	c2aDist: Number,
	a2bTime: String,
	b2cTime: String,
	c2aTime: String,
	fuelPrice: Number,
	cv: Number,
	vansNeeded: Number,
	staffReq: Number,
	loadTimeNet: Number,
	unloadTimeNet: Number,
	porterWages: Number,
	driverWages: Number,
	wages: Number,
	finalPrice: Number,
	workTime: Number,
	margin: Number,
	heaviestItem: Number,
	highestItem: Number,
	biggestVol: Number,
	notes: String,
	workTimeDisplay: String,
	movePrice: Number,
	endTime: String,
	dismantleArray: {},
	protArray: {},
	extraDismantleTime: Number,
	extraProtTime: Number,
	dismantleOptionsArray: {},
	dashboardShow: Boolean,
});

// create the model for users and expose it to our app
module.exports = mongoose.model('Quote', quoteSchema);


/*var itemSchema = {
	itemsid: Number,
    item: String,
    cubicFeet: Number,
    height: Number,
    width: Number,
    length: Number,
    weight: Number,
    dismantle: Boolean,
    dismantleTime: Number,
    assembly: Boolean,
    assemblyTime: Number,
    protection: Boolean,
    protectionTime: Number,
    materialsUsed: String,
    materialsQuantity: Number,
    location: String,
}*/
